name: plist
version: 1.0.1
author: Ole Martin Gjersvik <olem@olem.org>
description: A parser for the Property list xml format.
homepage: https://github.com/gjersvik/plist
documentation: http://www.dartdocs.org/documentation/plist/1.0.0/index.html
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  crypto: '>=0.9.0'
  xml: '>=2.0.0'
dev_dependencies:
  test: ^1.6.0
